server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/emazon_stock
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update


appDescription: "stockmicroservice"
appVersion: "1.0.0"